name: MiniBlocks
version: ${project.version}
main: com.tiffnix.miniblocks.MiniBlocks
api-version: 1.16
authors: [ Tiffnix ]
depend:
  - NBTAPI
description: A port of VanillaTweaks' player heads data packs to Spigot
